export const hyderabadLocations = [
  "Hyderabad",
  "A G Colony",
  "A S Rao Nagar",
  "Aaditya Nagar",
  "Abdullapurmet",
  "Abids",
  "AC Guards",
  "Adarsh Enclave",
  "Adarsh Nagar",
  "Afzalgunj",
  "Aghapura",
  "Ahmed Nagar",
  "Akbar Road",
  "Alexander Road",
  "Aliabad",
  "Alkapur Township",
  "Almasguda",
  "Alwal",
  "Ambedkar Nagar",
  "Amber Nagar",
  "Amberpet",
  "Ameerpet",
  "Ameerpet X Road",
  "Anand Bagh",
  "Anand Nagar Colony",
  "Ananthagiri",
  "Ankireddypalli",
  "Appa Junction",
  "AS Rao Nagar",
  "Ashok Nagar",
  "Asif Nagar",
  "Athvelly",
  "Attapur",
  "Attapur Ring Road",
  "Auto Nagar",
  "Azamabad",
  "Azampura",
  "Baber Bagh",
  "Bachupally",
  "Badangpet",
  "Badichowdi",
  "Bag Amberpet",
  "Bagh Lingampally",
  "Bahadurpally",
  "Bahadurpura",
  "Bairamalguda",
  "Bakaram",
  "Balamrai",
  "Balanagar",
  "Balapur",
  "Balkampet",
  "Bandimet",
  "Bandlaguda",
  "Bandlaguda Jagir",
  "Banjara Hills",
  "Bansilalpet",
  "Bapuji Nagar",
  "Barkas",
  "Barkatpura",
  "Basheer Bagh",
  "Bazar Ghat",
  "Begum Bazaar",
  "Begumpet",
  "Bhagya Nagar Colony",
  "Bharat Nagar",
  "BHEL",
  "Bhogaram",
  "Bholakpur",
  "Bhongir",
  "Bhuvanagiri",
  "Bibinagar",
  "BK Guda",
  "BN Reddy Nagar",
  "Boduppal",
  "Bogaram",
  "Boggulakunta",
  "Boiguda",
  "Bolarum",
  "Bollaram",
  "Bongloor",
  "Borabanda",
  "Bowenpally",
  "Bowrampet",
  "Boyiguda",
  "Brahim Patnam",
  "Buddha Nagar",
  "Budwel",
  "Burgul",
  "Champapet",
  "Chanda Nagar",
  "Chandanagar",
  "Charminar",
  "Chikkadpally",
  "Chinta Basti",
  "Chintal",
  "Chinthal Basti",
  "Chiran Fort Clubra",
  "Chowmohalla",
  "Dabeerpura",
  "Dabeerpura North",
  "Dadar Colony",
  "Dammaiguda",
  "Darul Shifa",
  "Defence Colony",
  "Devan Devdi",
  "Dhoolpet",
  "Dilsukhnagar",
  "Doddapet",
  "Doodh Bowli",
  "Domalguda",
  "Domara Pocham Pally",
  "Dorabavi",
  "Durga Bhawani Nagar",
  "ECIL",
  "Ecil Post",
  "Ecil X Roads",
  "East Anandbagh",
  "East Marredpally",
  "Erragadda",
  "Erramanzil",
  "Film Nagar",
  "Gachibowli",
  "Gaddiannaram",
  "Ganapathi Nagar",
  "Gandhi Nagar",
  "Ghoshamahal",
  "Golconda",
  "Gopanpally",
  "Gowliguda",
  "Goud Nagar",
  "Gulzar Houz",
  "Gummadidala",
  "Hafeezpet",
  "Hakeempet",
  "Hajipalle",
  "Hanuman Nagar",
  "Hans Nagar",
  "Happy Homes Colony",
  "Haripuri Colony",
  "Hayath Nagar",
  "HCL Colony",
  "HMT Colony",
  "HMT Hills",
  "Himayath Nagar",
  "Hussaini Alam",
  "Hyderguda",
  "IDPL Colony",
  "IDC Colony",
  "Ibrahim Bagh",
  "Ibrahimpatnam",
  "Icrisat Enclave",
  "Indira Nagar",
  "Indira Nagar Colony",
  "Inole",
  "Ismailkhanpet",
  "Jahanuma",
  "Jaihindpuram",
  "Jameen Bazar",
  "Jubilee Hills",
  "JNTU Colony",
  "Kachiguda",
  "Kalkaji Colony",
  "Kamala Nagar",
  "Kamalapuri Colony",
  "Kavadiguda",
  "Kavuri Hills",
  "Keerthanagar",
  "Khairatabad",
  "Kollur",
  "Kondapur",
  "Kothaguda",
  "Kothapet",
  "KPHB Colony",
  "Kukatpally",
  "Kukatpally Housing Board",
  "Lakdikapul",
  "Lingampally",
  "Madhapur",
  "Madhura Nagar",
  "Mahendra Hills",
  "Malkajgiri",
  "Malakpet",
  "Manikonda",
  "Maruthi Nagar",
  "Miyapur",
  "Moghalpura",
  "Moula Ali",
  "Mulugu",
  "Moti Nagar",
  "Nagole",
  "Nallakunta",
  "Nallagandla",
  "Narayanaguda",
  "Nasrullahpura",
  "Naya Nagar",
  "Nehru Nagar",
  "Neredmet",
  "Nizampet",
  "NTR Nagar",
  "Old Alwal",
  "Osman Nagar",
  "Padmarao Nagar",
  "Panjagutta",
  "Parsigutta",
  "Patancheru",
  "Peerzadiguda",
  "Picket",
  "Pillalaramaram",
  "Pochampally",
  "Punjagutta",
  "Puppalaguda",
  "Quthbullapur",
  "Rahmania Nagar",
  "Raghavendra Nagar Colony",
  "Rajendranagar",
  "Ramanthapur",
  "Ramnagar",
  "Red Hills",
  "RTC X Roads",
  "Sainikpuri",
  "Sanathnagar",
  "Santosh Nagar",
  "Secunderabad",
  "Shadnagar",
  "Shamirpet",
  "Shantinagar",
  "Shamshabad",
  "Shivamguda",
  "Siddiq Nagar",
  "Sitaphalmandi",
  "SR Nagar",
  "SRT Colony",
  "Tadbund",
  "Talaab Katta",
  "Talabkatta",
  "Taramatipet",
  "Tarnaka",
  "Tellapur",
  "Toli Chowki",
  "Uppal",
  "Uppal Kalan",
  "Usha Nagar",
  "Vanasthalipuram",
  "Vattepally",
  "Vengal Rao Nagar",
  "Vidyanagar",
  "Warasiguda",
  "West Marredpally",
  "Yadagirigutta",
  "Yakutpura",
  "Yapral",
  "Yellareddy Guda",
  "Yousufguda",
  "Zameerbagh",
  "Zamistanpur",
  "Hitech City",
  "Hi Tech City",
  "Jeedimetla",
  "Financial District",
  "Nanakramguda",
  "Raidurg",
  "Raidurgam",
  "Kokapet",
  "Narsingi",
  "Tellapur Phase 2",
  "Kompally",
  "Medchal",
  "Suchitra",
  "Suchitra Circle",
  "Keesara",
  "Turkapally",
  "Pocharam",
  "Pocharam IT Park",
  "Adibatla",
  "Tukkuguda",
  "Maheshwaram",
  "Shankarpally",
  "Kothur",
  "Chevella",
  "Moinabad",
  "Gandipet",
  "Neknampur",
  "Alkapuri",
  "Kapra",
  "Safilguda",
  "Dr AS Rao Nagar",
  "Chintalakunta",
  "Meerpet",
  "LB Nagar X Roads",
  "Hasthinapuram",
  "Karmanghat",
  "Moosapet",
  "Pragathi Nagar",
  "Mallapur",
  "Nacharam",
  "Upparpally",
  "Santoshnagar Colony",
  "Raj Bhavan Road",
  "Somajiguda",
  "Greenlands",
  "Begumpet Airport Area",
  "Trimulgherry",
  "Mettuguda",
  "Tarnaka X Roads",
  "Secunderabad Cantonment",
  "Kondakal",
  "Velimela",
  "Osman Sagar Road",
  "Kollur ORR Exit",
  "Tellapur ORR",
  "Nallagandla Extension",
  "Serilingampally",
  "Masjid Banda",
  "Anjaiah Nagar",
  "Botanical Garden Road",
  "Gowlidoddy",
  "Indira Nagar Gachibowli",
  "Telecom Nagar",
  "DLF Road",
  "Raidurg Panmaktha",
  "Shaikpet",
  "Manikonda Jagir",
  "Puppalaguda Main Road",
  "Khajaguda Hills",
  "Alkapoor Township Road",
  "OU Colony Manikonda",
  "Sri Ram Nagar Kondapur",
  "Raghavendra Colony Kondapur",
  "My Home Bhooja",
  "My Home Avatar",
  "My Home Mangala",
  "My Home Vihanga",
  "Prestige High Fields",
  "Prestige Ivy League",
  "Aparna Sarovar",
  "Aparna CyberZon",
  "Aparna Kanopy",
  "Aparna Zenon",
  "Aparna Serene Park",
  "Aparna Elixir",
  "Ramky One Kosmos",
  "Ramky Towers",
  "Lansum Etania",
  "DSR Fortune Prime",
  "SMR Vinay City",
  "Indis One City",
  "Golf Edge",
  "Lodha Meridian",
  "Jayabheri Orange County",
  "Jayabheri Silicon County",
  "Vertex Panache",
  "Vertex Homes",
  "Sri Aditya Athena",
  "Mindspace Madhapur",
  "Cyber Towers Area",
  "Cyber Gateway",
  "RMZ Nexity",
  "WaveRock SEZ",
  "Salarpuria Sattva Knowledge City",
  "Divyasree Orion",
  "Ascendas IT Park",
  "Amazon Campus Gachibowli",
  "Microsoft Campus",
  "Wipro Circle",
  "ISB Road",
  "IIIT Hyderabad Area",
  "Nanakramguda Financial District Road",
  "Mucherla Pharma City",
  "Kandukur",
  "Choutuppal",
  "Yacharam",
  "Kongarakalan",
  "Hardware Park",
  "Fab City",
  "E City Hyderabad",
  "Kandukur Road",
  "Adibatla Aerospace Park",
  "Road No 36 Jubilee Hills",
  "Road No 45 Jubilee Hills",
  "Road No 10 Banjara Hills",
  "Road No 12 Banjara Hills",
  "Film Nagar Phase 1",
  "Film Nagar Phase 2",
  "Journalist Colony Jubilee Hills",
  "MLA Colony Banjara Hills",
  "KPHB Phase 1",
  "KPHB Phase 2",
  "KPHB Phase 3",
  "KPHB Phase 4",
  "KPHB Phase 5",
  "KPHB Phase 6",
  "KPHB Phase 7",
  "Miyapur Allwyn Colony",
  "New Hafeezpet",
  "Old Hafeezpet",
  "Chandanagar Railway Colony",
  "Aparna Moonstone",
  "Aparna Newlands",
  "Aparna Synergy",
  "Aparna Sarovar Towers",
  "Aparna Greenscapes",
  "Aparna CyberOn",
  "Aparna Deccan Town",
  "Aparna Serenity",
  "My Home Udyan",
  "My Home Akrida",
  "My Home Grava",
  "My Home Apas",
  "My Home 99",
  "My Home Avali",
  "My Home Vipina",
  "My Home Nishada",
  "My Home Sayuk",
  "My Home Raka",
  "My Home Tridasa",
  "My Home Krishe",
  "Prestige Clairemont",
  "Prestige Beverly Hills",
  "Prestige Tranquil",
  "Prestige Vaishnaoi Rainbow Waters",
  "The Prestige City Hyderabad",
  "Prestige Spring Heights",
  "Myscape Songs of the Sun",
  "YOO Hyderabad",
  "The Loft",
  "Sumadhura Horizon",
  "The Olympus by Sumadhura",
  "Sumadhura Acropolis",
  "Sumadhura Palais Royale",
  "Gardens by the Brook",
] as const;
